name: Post JSON File to Two URLs

on:
  push:
    branches:
      - main # Runs only when pushing to the main branch
  workflow_dispatch: # Allows manual trigger
  
jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:XGcLglQaTE6_CIYEDIljcg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:GgLZLtEKTzSlAt5ZVb9D9Q/streams/AQAAAKp6hItJbkc4nzoaSU6GgVEAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json
            
      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:ghCA2c45SzSztjYAF8S2-g@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:GgLZLtEKTzSlAt5ZVb9D9Q/streams/AQAAAI1L_K752UZ8mE7-douDsGwAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json
